### ISSUE TITLE
Remove restrictions on mobileness

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#306] opened 2022-06-13 12:20 UTC
Document draft contains the following paragraph.

> User Agents MUST return the empty string for model if mobileness is false. User Agents MUST return the empty string for model even if mobileness is true, except on platforms where the model is typically exposed.

This paragraph should be removed and the decision left to the implementor to decide.

For example; Google's security features show the Windows device model to help user's differentiate between different Windows devices even when they are not mobile. Implementors should be able to offer this feature without contravening the specification.

**Comment by miketaylr** [comment] 2022-06-13 16:53
@jwrosewell can you please upload a screenshot or same link for the security feature you're describing? I'm not familiar with it, but am curious what you mean by device model - that isn't exposed in Windows desktop UA strings AFAIK.

**Comment by jwrosewell** [comment] 2022-06-13 18:42
![image](https://user-images.githubusercontent.com/1679482/173422390-3bba04f1-aa5e-4855-8857-41d1c64ed2ec.png)

Shows the name of the Windows computer used which I've blanked out with the red box.

![image](https://user-images.githubusercontent.com/1679482/173422788-54e0906d-b66c-47e1-8ba1-f9c3a1f7ff77.png)

Shows the model of the Windows device used.

**Comment by miketaylr** [comment] 2022-07-01 14:50
This sounds like a duplicate of https://github.com/WICG/ua-client-hints/issues/67 - thanks for filing the issue.

**Closed by miketaylr** 2022-07-01 14:50 UTC
