### ISSUE TITLE
Don't send `Sec-CH-UA` at all, unless requested

### ISSUE THREAD

**Issue by snyderp** [WICG/ua-client-hints#1] opened 2019-04-19 23:29 UTC
First off, I think this is all a great idea :)

Suggestion: my expectation is that for the vast majority of web requests, even the `Sec-CH-UA` is unnecessary.  On top of that, the web platform has been telling everyone to ignore the UA anyway and feature detect or similar since way back.

Whats the thinking behind still including it by default in every request in the proposal?  If you're suggesting we change the game, I suggest not sending `Sec-CH-UA` by default either.

If the decision in the proposal is guided by #s Chrome has, thats equally interesting!  If thats the case, anything you could share would be really neat :)

**Comment by yoavweiss** [comment] 2020-01-16 08:45
While it is tempting, there are a few legitimate use cases for the coarse grained UA info. Unfortunately, there's no replacement for it when working around known bugs, as well as when deciding which polyfills a site should send down to the browser, which version of ES it supports, etc.

Because the Client Hints framework doesn't yet have an opt-in method that can work on the very first request to a site, forcing those use cases to go through an extra redirect seems like it would result in a non-negligable regression. We're willing to take that hit for sites that require granular information (e.g. device model, OS, etc), but for exposing extremely coarse information like the UA info, that seems excessive.

Once a very-first-hit opt-in mechanism is introduced, we may be able to revisit that.

**Comment by yoavweiss** [comment] 2020-01-16 09:22
Closing, as this is not actionable, but feel free to re-open if you feel this requires more discussion.

**Closed by yoavweiss** 2020-01-16 09:22 UTC
