### ISSUE TITLE
Determination of high and low entropy Client Hints

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#131] opened 2020-09-23 18:10 UTC
How are low and high entropy Client Hints determined in the Client Hints Infrastructure document? How are they balanced against considerations other than privacy? For example, a company with access to the equivalent data via other means such as a header sent only to their services might seek to restrict access to some values citing entropy as justification. This needs to be resolved before referencing in this document.

See [this pull request]( https://github.com/WICG/ua-client-hints/pull/124) which incorporates experiment feedback and review from interested users and other stakeholders for proposed text changes.

**Comment by yoavweiss** [comment] 2020-10-27 05:12
This seems like a duplicate of #134

**Closed by yoavweiss** 2020-10-27 05:12 UTC
