### ISSUE TITLE
Additional round trip impact on performance

### ISSUE THREAD

**Issue by Steve51D** [WICG/ua-client-hints#66] opened 2020-02-14 08:41 UTC
This has already been discussed to some extent [here ](https://github.com/WICG/ua-client-hints/issues/3) and [here](https://github.com/WICG/ua-client-hints/issues/2). There is also the start of a discussion on a solution [here](https://github.com/WICG/client-hints-infrastructure/issues/16). However, I still wanted to open this new issue as I don't feel that the scale of the potential impact has been fully appreciated.

Currently, the User-Agent is sent in the first request. If the website wants to act on this information in any way then it can do so before crafting it's response.

By moving to a system that requires an additional response & request when some of this information is needed for any reason, we are introducing a performance penalty.

It may be tempting to brush this off as insignificant and that is probably true when using a high spec smartphone on a good connection, but this becomes more of a problem in areas with poor mobile network coverage, which is a significant problem in developing countries.

Any web developer knows the value of [reducing page load times](https://blog.hubspot.com/marketing/page-load-time-conversion-rates) and this proposal will negatively impact page load times for those on poor connections.

**Comment by amtunlimited** [comment] 2020-02-15 03:31
> By moving to a system that requires an additional response & request when some of this information is needed for any reason, we are introducing a performance penalty.

This isn't entirely accurate. The spec says to store the preferences after it sees them, and this includes all subsequent 1p requests, navigation or otherwise. This doesn't have a lifetime associated other than an action taken to clear information about an origin (resetting a session, clearing cookies, clear-site-data, etc.), so we're only talking about the very first navigation request. All other requests will have the previous opt-ins (unless the opt-ins change).

This is still a problem that needs to be solved, though.

**Comment by yoavweiss** [comment] 2020-03-14 22:25
There's an open issue on Client Hints in general for this: https://github.com/WICG/client-hints-infrastructure/issues/16

Generally, this is a problem I'm super interested in solving. The reason that didn't seem blocking for UA-CH was the assumptions that:
* The hints sent by default (brand, significant version and mobileness) are enough to perform most content adaptations without an extra RTT.
* The problem is limited to the "very first view" case (as @amtunlimited pointed out)

I've since heard of some use cases with data that breaks those assumptions.

**Comment by yoavweiss** [comment] 2020-04-29 08:21
Can we close this? It doesn't seem actionable (other than recording support for solving the "0 RTT opt-in" problem)

**Comment by Steve51D** [comment] 2020-04-29 15:36
My feeling is that the client-hints proposal seems incompatible with guaranteeing websites access to what they need on the first request as it's all about putting that choice in the hands of the user (or the browser developer).
I think it's a big enough problem that the proposal simply should not go ahead, but I agree that it's not really actionable without fundamentally redefining what UA-CH is trying to do.

**Comment by jonarnes** [comment] 2020-04-29 18:09
I've been in the "user-agent dependent" business long enough to know that there is a lot of dependencies of device- and browser info on first page view. I can easily see sites being forced implement an additional roundtrip, or other hacks, to get the info their application needs. But yea, no firm evidence and no actionable items. 
I know that the freezing of the user-agent has been postponed. Maybe the action can be to postpone the user-agent freeze until UA-CH can be a complete alternative to the user-agent including UA-CH presence on first page view. 
I don't see any reason why UA-CH must _replace_ the user-agent through a freeze. Until UA-CH has a solution for the first page view, the two could live happily side by side and provide the same, unfrozen, information.

**Comment by miketaylr** [comment] 2021-01-22 17:01
I believe https://tools.ietf.org/html/draft-davidben-http-client-hint-reliability-02 addresses this, no?

**Comment by miketaylr** [comment] 2021-03-22 21:42
I'm going to close this, given the Client Hints Reliability proposal which provides 2 mechanisms to solve the described problem:  https://github.com/WICG/client-hints-infrastructure/blob/master/reliability.md

(Any further issues on that topic would probably be better in the client-hints-infrastructure repo than here, I think.)

**Closed by miketaylr** 2021-03-22 21:42 UTC
Labels: Discussion

**Comment by ronancremin** [comment] 2021-03-22 23:53
Is it reasonable to close this? The Client Hints Reliability proposal is exactly that—a proposal. Closing this issue might signal that the problem is solved when in fact only a proposal exists, and that proposal is controversial, since it blurs the lines between protocol layers.

**Comment by miketaylr** [comment] 2021-03-23 14:24
> Is it reasonable to close this?

I think it is. 2 months passed between me suggesting that Client Hints Reliability addresses this issue and closing it. In the meantime no other participants suggested otherwise.

> The Client Hints Reliability proposal is exactly that—a proposal.

Sure, a proposal that should soon be testable so we can gather feedback and possibly improve upon (see, e.g., https://groups.google.com/a/chromium.org/g/blink-dev/c/V3Yo20_ZZLc/m/rUT-qELKBwAJ).

@ronancremin if you have an alternative, concrete proposal to be considered, I think the right place to open that will be the client-hints-infrastructure repo, since any (alternative) solution will be handled by that spec (If we come up with a better solution I can't imagine that we would restrict it to only UA Client Hints).

**Comment by Steve51D** [comment] 2021-03-23 15:22
For what it's worth, my opinion hasn't changed from my last comment on here: 

> My feeling is that the client-hints proposal seems incompatible with guaranteeing websites access to what they need on the first request as it's all about putting that choice in the hands of the user (or the browser developer).
I think it's a big enough problem that the proposal simply should not go ahead, but I agree that it's not really actionable without fundamentally redefining what UA-CH is trying to do.
